isuuetracker/Controllers/pmController.cs
using isuuetracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace isuuetracker.Controllers
{
    public class pmController : Controller
    {
        // GET: pm
        public ActionResult assign()
        {
            Modelclass model = new Modelclass();
            try
            {
                datamodel data = new datamodel();
                int j = (int)Session["id"];
                string job = data.roles.Where(i => i.userid == j).Select(i => i.work).FirstOrDefault();
                if (job == "PM")
                {
                    
                }
                else
                {
                    return RedirectToAction("login", "login");
                }
            }
            catch
            {
                return RedirectToAction("login", "login");
            }
            return View();
          
        }
       
        public ActionResult edit(string pid , int bid)
        {
            Modelclass model = new Modelclass();
            try
            {
                datamodel data = new datamodel();
                int j = (int)Session["id"];
                ViewBag.bid = bid;
                string job = data.roles.Where(i => i.userid == j).Select(i => i.work).FirstOrDefault();
                if (job == "PM")
                {
                    int projm = data.projects.Where(i => i.projectname == pid).Select(i => i.projectid).FirstOrDefault();
                    var devs = data.roles.Where(i => i.work == "DEV" && i.projectid == projm).Select(i => i.userid);
                    foreach (var n in devs)
                    {
                        var p = data.logins.Where(i => i.loginId == n).FirstOrDefault();
                        model.dev.Add(new SelectListItem() { Text = p.username, Value = p.loginId.ToString() });
                    }


                }
                else
                {
                    return RedirectToAction("login", "login");
                }
            }
            catch
            {
                return RedirectToAction("login", "login");
            }
            return View(model);

        }
        [HttpPost]
        public ActionResult edit(Modelclass model, int bid)
        {
            datamodel data = new datamodel();
            bugpool bugs = data.bugpools.Where(i => i.bugid == bid).Select(i => i).FirstOrDefault();
            history hist = new history();
            bugs.assigntoId = model.devid;
            bugs.status = "Assigned";
            
            data.SaveChanges();
            hist.bugid = bugs.bugid;
            hist.ModifieduserId = (int)Session["id"];
            hist.comment = model.comments;
            hist.status = bugs.status;
            hist.time = DateTime.Now;
            data.historys.Add(hist);
            data.SaveChanges();
            return Redirect("/testing/dashboard");
        }
        public ActionResult status(int bid)
        {
            Modelclass model = new Modelclass();
            try
            {
                datamodel data = new datamodel();
                int j = (int)Session["id"];
                string job = data.roles.Where(i => i.userid == j).Select(i => i.work).FirstOrDefault();
                if (job !=null)
                {
                    List<Modelclass> modellist = new List<Modelclass>();
                    var hist = data.historys.Where(i => i.bugid == bid);
                    foreach (var val in hist)
                    {

                       string user = data.logins.Where(i => i.loginId == val.ModifieduserId).Select(i => i.username).FirstOrDefault();
                        string role = data.roles.Where(i => i.userid == val.ModifieduserId).Select(i => i.work).FirstOrDefault();
                        modellist.Add(new Modelclass() { username=user , status=val.status, comments=val.comment,time=val.time,job=role });
                    }
                    return View(modellist);
                }
                else
                {
                    return RedirectToAction("login", "login");
                }
            }
            catch
            {
                return RedirectToAction("login", "login");
            }
            
        }
    }
}

isuuetracker/Controllers/testingController.cs
using isuuetracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace isuuetracker.Controllers
{
    public class testingController : Controller
    {
        // GET: testing
        public ActionResult bug()
        {
            ViewBag.msg = "BUG Report";
            Modelclass model = new Modelclass();
            try
            {
                datamodel data = new datamodel();
                int j = (int)Session["id"];
                var role= data.roles.Where(i => i.userid == j);
                string job = role.Select(i=>i.work).FirstOrDefault();
                if (job=="TESTER")
                {
                    var projnm = role.Select(i => i.projectid);
                    foreach (var n in projnm)
                    {
                        var p = data.projects.Where(i => i.projectid == n).FirstOrDefault();
                        model.projectlist.Add(new SelectListItem() { Text = p.projectname, Value = p.projectid.ToString() });
                    }
                    SelectListItem[] list = new SelectListItem[3];
                    list[0] = new SelectListItem() { Text = "Blocking", Value = "Blocking" };
                    list[1] = new SelectListItem() { Text = "High Priority", Value = "High" };
                    list[2] = new SelectListItem() { Text = "Low Priority", Value = "Low" };
                    ViewBag.list = list;
                }
                else
                {
                    return RedirectToAction("login", "login");
                }
            }
            catch
            {
                return RedirectToAction("login", "login");
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult bug(Modelclass model)
        {
            datamodel data = new datamodel();
            bugpool bugs = new bugpool();
            history hist = new history();
            int j= (int)Session["id"];
            bugs.testerid = j;
            bugs.projectid = int.Parse(model.projid);
            bugs.bugname = model.bugname;
            bugs.bugtype = model.bugtype;
            bugs.status = "Open";
            data.bugpools.Add(bugs);
            data.SaveChanges();
            hist.bugid = bugs.bugid;
            hist.ModifieduserId = bugs.testerid;
            hist.comment = model.comments;
            hist.status = bugs.status;
            hist.time = DateTime.Now;
            data.historys.Add(hist);
            data.SaveChanges();
            return Redirect("/testing/dashboard");
        }
        public ActionResult dashboard()
        {
            Modelclass model = new Modelclass();
            try
            {
                datamodel data = new datamodel();
                int j = (int)Session["id"];
                var role = data.roles.Where(i => i.userid == j);
                string job = role.Select(i => i.work).FirstOrDefault();
                List<Modelclass> modellist = new List<Modelclass>();
                if (job!=null)
                {

                     if (job == "TESTER")
                    {
                        var info = data.bugpools.Where(i => i.testerid == j).Select(i => i);
                        foreach (var val in info)
                        {
                            var proj = data.projects.Where(i => i.projectid == val.projectid).Select(i=> i.projectname).FirstOrDefault();
                            modellist.Add(new Modelclass() { status=val.status, bugname=val.bugname, projid=proj, bugtype=val.bugtype,bugid=val.bugid,job=job  });
                        }
                    }
                    else if (job == "DEV")
                    {

                        var info = data.bugpools.Where(i => i.assigntoId == j).Select(i => i);
                        foreach (var val in info)
                        {
                            var proj = data.projects.Where(i => i.projectid == val.projectid).Select(i => i.projectname).FirstOrDefault();
                            modellist.Add(new Modelclass() { status = val.status, bugname = val.bugname, projid = proj, bugtype = val.bugtype, bugid = val.bugid,job=job });
                        }
                    }
                    else if (job == "PM")
                    {

                        var projnm = role.Select(i => i.projectid);
                        
                        
                        foreach (var val in projnm)
                        {
                            var devs = role.Where(i => i.work == "DEV" && i.projectid == val).Select(i => i.userid);
                            foreach (var n in devs)
                            {
                                var p = data.logins.Where(i => i.loginId == n).FirstOrDefault();
                                model.dev.Add(new SelectListItem() { Text = p.username, Value = p.loginId.ToString() });
                            }
                            var info = data.bugpools.Where(i=> i.projectid==val).Select(i => i);
                            foreach(var bg in info)
                            {
                                var proj = data.projects.Where(i => i.projectid == bg.projectid).Select(i => i.projectname).FirstOrDefault();
                                modellist.Add(new Modelclass() { status = bg.status, bugname = bg.bugname, projid =proj , bugtype = bg.bugtype, bugid = bg.bugid, job=job });
                            }
                            
                        }
                           
                    }
                    
                    return View(modellist);
                }
                else
                {
                    return RedirectToAction("login", "login");
                }
            }
            catch
            {
                return RedirectToAction("login", "login");
            }
        }
        public ActionResult open(int bid)
        {
            Modelclass model = new Modelclass();
            try
            {
                datamodel data = new datamodel();
                int j = (int)Session["id"];
                var role = data.roles.Where(i => i.userid == j);
                string job = role.Select(i => i.work).FirstOrDefault();
                if (job == "TESTER")
                {
                    ViewBag.bid = bid;
                }
                else
                {
                    return RedirectToAction("login", "login");
                }
            }
            catch
            {
                return RedirectToAction("login", "login");
            }
            return View(model);
        }
    
        [HttpPost]
        public ActionResult open(int bid,Modelclass model)
        {
            datamodel data = new datamodel();
            bugpool bugs = data.bugpools.Where(i => i.bugid == bid).Select(i => i).FirstOrDefault();
            history hist = new history();
            bugs.status = "Open";

            data.SaveChanges();
            hist.bugid = bugs.bugid;
            hist.ModifieduserId = (int)Session["id"];
            hist.comment = model.comments;
            hist.status = bugs.status;
            hist.time = DateTime.Now;
            data.historys.Add(hist);
            data.SaveChanges();
            return Redirect("/testing/dashboard");

            
        }
        public ActionResult close(int bid)
        {
            Modelclass model = new Modelclass();
            try
            {
                datamodel data = new datamodel();
                int j = (int)Session["id"];
                var role = data.roles.Where(i => i.userid == j);
                string job = role.Select(i => i.work).FirstOrDefault();
                if (job == "TESTER")
                {
                    ViewBag.bid = bid;
                }
                else
                {
                    return RedirectToAction("login", "login");
                }
            }
            catch
            {
                return RedirectToAction("login", "login");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult close(int bid, Modelclass model)
        {
            datamodel data = new datamodel();
            bugpool bugs = data.bugpools.Where(i => i.bugid == bid).Select(i => i).FirstOrDefault();
            history hist = new history();
            bugs.status = "Closed";

            data.SaveChanges();
            hist.bugid = bugs.bugid;
            hist.ModifieduserId = (int)Session["id"];
            hist.comment = model.comments;
            hist.status = bugs.status;
            hist.time = DateTime.Now;
            data.historys.Add(hist);
            data.SaveChanges();
            return Redirect("/testing/dashboard");


        }
    }
}

isuuetracker/Views/pm/assign.cshtml
@{
    ViewBag.Title = "assign";
}
@{ Html.RenderAction("dashboard", "testing");}

isuuetracker/Views/pm/edit.cshtml
@model isuuetracker.Models.Modelclass
@{
    ViewBag.Title = "edit";
    Layout = "";
}
<style type="text/css">
    option {
        border: none;
        color: black;
        background-color: white;
        width: 200px;
    }
    textarea {
        border-radius: 4px;
        width: 200px;
    }
    #sub {
        border: none;
        background-color: lightskyblue;
        font-weight: 600;
        
        
    }
    span {
        font-weight: 600;
    }
    .l {
        padding:10px;
        position: absolute;
        top: 25%;
        left: 40%;
        width: auto;
        height: auto;
        text-align: center;
        background-color: white;
        border-radius: 5px;
    }
    select {
        background-color: lightblue;
        color: white;
        padding: 10px;
        font-size: 16px;
        border: none;
        cursor: pointer;
        border-radius: 4px;
        width:200px;
    }
</style>

<div class="l">
    <div>
        <button type="button" class="close " data-dismiss="modal"><span>&times;&nbsp;</span></button>
        <h4 class="text-primary">Assign To Developer</h4>
    </div>
    <hr />
   @using (Html.BeginForm("edit", "pm", FormMethod.Post))
   {
      <table cellpadding="8">
          <tr>
              <td>
                  <span>Developer</span>
              </td>
              <td>
                 :
              </td>
              <td>
                  @Html.DropDownListFor(m => m.devid, Model.dev , new { @class="btn-info"})
              </td>
          </tr>
          <tr>
              <td>
                  <span>Comments </span>
              </td>
              <td>
                  :
              </td>
              <td>
                 @Html.TextAreaFor(m => m.comments, new { required = "Required" })
              </td>
          </tr>
          <tr>
              <td>
                  
              </td>
              <td>
                  
              </td>
              <td align="right">
                  <input type="submit"   class="btn btn-primary" id="sub" value="Submit" />
              </td>
          </tr>
      </table>
   
   
    <input type="hidden" value="@ViewBag.bid" name="bid">
   
   }

    <hr />
    <p class="text-warning">*Assign this to concern Developer</p>
</div>

isuuetracker/Views/pm/status.cshtml
@model List<isuuetracker.Models.Modelclass>
@{
    ViewBag.Title = "status";
}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">UserName</th>
            <th scope="col">Role</th>
            <th scope="col">status</th>
            <th scope="col">Comment</th>
            <th scope="col">Time</th>
           
        </tr>
    </thead>
    @foreach (var i in Model)
    {

        <tr scope="row">
            <td>
                @i.username
            </td>
            <td>
                @i.job
            </td>
            <td>
                @if (i.status == "Closed")
                {
                    <p class="text-success">@i.status</p>
                }
                @if (i.status == "Open")
                {
                    <p class="text-danger">@i.status</p>
                }
                @if (i.status == "Assigned")
                {
                    <p class="text-warning">@i.status</p>
                }
                @if (i.status == "Resolved")
                {
                    <p class="text-success">@i.status</p>
                }

            </td>
            <td>
                @i.comments
            </td>
            <td>
                @i.time
            </td>
            

        </tr>


    }
</table>